version: "3"

################################################################################################
#
# local dev:
#   - run:
#   - clean:
#
################################################################################################

#
# global vars: https://taskfile.dev/#/usage?id=variables
#
vars:
  VAR1: "var1"

# global env:
env:
  ENV1: testing

# env file:
dotenv:
  - .env

################################################################################################

# task groups:
tasks:
  default:
    cmds:
      - task: init
      - task: run

  setup:
    cmds:
      - curl -fsSL https://github.com/Schniz/fnm/raw/master/.ci/install.sh | bash -s -- --force-install
      - fnm -V
      - fnm install v16.13.1
      - fnm use v16.13.1
      - node -v
      - npm -v
      - npm install -g yarn

  install:
    cmds:
      - yarn

  run:
    cmds:
      - yarn start

  init:
    cmds:
      - task: init:env
      - task: install

  init:env:
    cmds:
      - cp .env.local .env
      - cp .env.test test/.env

  #########################################################################

  clean:
    cmds:
      - yarn clean

  #
  # 每次升级 flutter 版本, 要执行 clean + run, 否则报奇怪错误.
  #
  clean:run:
    cmds:
      - task: clean
      - task: run

  release:
    cmds:
      - yarn build
